apiVersion: apps/v1
kind: Deployment
metadata: 
  name: myapp-deployment1
  labels:
    app: myapp1
spec: 
  selector:
    matchLabels:
      app:  myapp1
  replicas: 6
  strategy:
    type: Recreate
  template:
    metadata:
      name: nginx-2
      labels: 
        app:  myapp1
    spec:
      containers:
        - name: nginx
          image: nginx

        