apiVersion: apps/v1
kind: Deployment
metadata: 
  name: myapp-upgrade
  labels:
    app: myappupgrade
spec: 
  selector:
    matchLabels:
      app:  myappupgrade
  replicas: 6
  template:
    metadata:
      name: nginx-2
      labels: 
        app:   myappupgrade
    spec:
      containers:
        - name: nginx
          image: nginx

        