apiVersion: v1
kind: Service
metadata:
  name: myapp-pod-nodeport-service 
spec:
  type: NodePort 
  selector:
    app: myapp 
  ports: 
    - name: http
      port: 7000 # ArbitaryService Port
      targetPort: 7000 #ContainerPort
      nodePort: 31231 # NodePort